package com.tripnest.tripnest_backend.model;

public enum NotificationType {
    TRIP_INVITATION,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    MEMBER_ADDED,
    JOIN_REQUEST_SUBMITTED,
    JOIN_REQUEST_APPROVED,
    JOIN_REQUEST_REJECTED,
    TRIP_UPDATE,
    TRIP_REMINDER,
    ACTIVITY_REMINDER,
    BUDGET_ALERT,
    GENERAL
}
